import React from 'react';
import { Helmet } from 'react-helmet';
import Footer from '@/components/Footer';
import {
  Page, Breadcrumb, PageHero, Section, SectionHeader, Button, Icon, ProofPanel, FAQ,
} from '@/brand/components';
import LeadForm from '@/brand/LeadForm';
import { AskAi } from '@/brand/Illustrations';

const faqs = [
  {
    q: 'What exactly is AI Search Visibility?',
    a: 'AI Search Visibility is your brand\'s ability to appear in answers generated by AI tools like ChatGPT, Google AI Overviews, Perplexity, and Gemini. When someone asks an AI "what\'s the best physio in Bangkok?" or "top SEO agency in Thailand," AI search visibility determines whether your brand gets named — or whether a competitor does.'
  },
  {
    q: 'How is this different from traditional SEO?',
    a: 'Traditional SEO optimises for rankings — your page shows up on Google and the user clicks it. AI search works differently. The AI reads hundreds of sources, synthesises them, and writes a direct answer. Your goal isn\'t to rank #1 on a list. Your goal is to be cited as a trusted source within that answer. We optimise for both, but the signals AI models rely on — entity authority, citation density, structured content — require a distinct strategy.'
  },
  {
    q: 'How long does it take to see results?',
    a: 'Most clients see measurable improvement in AI citation frequency within 60–90 days. The speed depends on your starting domain authority, how much content we\'re building, and how competitive your niche is. Technical and schema improvements can show impact faster — sometimes within 30 days. We track progress monthly and share transparent reporting.'
  },
  {
    q: 'Do you work with businesses outside Thailand?',
    a: 'Yes. The majority of our methodology is platform-agnostic — ChatGPT, Perplexity, and Gemini operate globally. We have clients in Bangkok, Singapore, and the UK. Local context matters for things like Google AI Overviews (which vary by country), and we factor that into strategy.'
  },
  {
    q: 'What industries benefit most from AI search optimisation?',
    a: 'Any business where people ask AI for a recommendation before making a decision. Healthcare and clinics, professional services, software, hospitality, finance, e-commerce, and education all see strong results. The higher the trust barrier in your industry, the more powerful an AI recommendation becomes — because users treat AI as an impartial expert.'
  },
  {
    q: 'Do you guarantee rankings?',
    a: 'No agency can guarantee specific AI placements — AI outputs are probabilistic by nature and shift as models are updated. What we guarantee is systematic, documented work across every signal that drives AI citation: content quality, entity recognition, structured data, citation building, and technical visibility. We track your citation rate monthly and optimise based on what\'s working.'
  }
];

const schemaService = {
  '@context': 'https://schema.org',
  '@type': 'Service',
  name: 'AI Search Visibility & SEO',
  serviceType: 'Generative Engine Optimization (GEO / AIO)',
  provider: { '@id': 'https://www.locully.org/#organization' },
  areaServed: [{ '@type': 'City', name: 'Bangkok' }, { '@type': 'Country', name: 'Thailand' }],
  url: 'https://www.locully.org/ai-search-visibility',
  description: 'Locully makes your brand the answer AI assistants give — optimizing entity authority, structured data, and citation signals so ChatGPT, Perplexity, Google AI Overviews, and Gemini recommend you.',
};

const schemaFaq = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map((f) => ({
    '@type': 'Question',
    name: f.q,
    acceptedAnswer: { '@type': 'Answer', text: f.a },
  })),
};

const shiftStats = [
  { stat: '47%', label: 'of Google searches now show AI Overviews' },
  { stat: '100M+', label: 'ChatGPT queries per day (Jan 2025)' },
  { stat: '4.4×', label: 'higher conversion from AI-referred leads' },
];

const signals = [
  { icon: 'doc', title: 'Content Authority', body: 'AI engines cite sources that demonstrate expertise. Long-form, factually dense content — structured with clear headings, direct answers, and specific claims — signals that your brand knows what it\'s talking about. Thin content doesn\'t get cited.' },
  { icon: 'globe', title: 'Entity Recognition', body: 'An entity is a clearly defined thing: a brand, a person, a product, a location. AI models rely on entity graphs to connect recommendations to the right context. We ensure your brand entity is well-defined, consistent, and linked across the web.' },
  { icon: 'link', title: 'Citation Signals', body: 'When authoritative third-party sources — publications, review platforms, industry directories — mention and link to your brand, it builds the trust profile AI models use to gauge credibility. Backlinks aren\'t just for Google.' },
  { icon: 'shield', title: 'Structured Data', body: 'Schema markup tells AI crawlers precisely what your business is, what it does, where it operates, and how it\'s been reviewed. Pages with clean structured data are significantly easier for AI engines to parse and recommend.' },
];

const methodology = [
  { step: '01', title: 'AI Visibility Audit', body: 'Before we touch anything, we test. We run structured queries across ChatGPT, Perplexity, Google AI Overviews, and Gemini — and document exactly how often your brand is mentioned, what context it\'s mentioned in, and how you compare to your direct competitors. This becomes your baseline. Every month, we measure against it.' },
  { step: '02', title: 'Content & Topical Authority', body: 'We audit your existing content and identify the gaps between what you\'ve published and what AI engines are citing in your niche. Then we build out a content plan — long-form articles, FAQs, comparison pieces, and opinion content — structured specifically to be cited as a source. This isn\'t blog writing. It\'s AI citation engineering.' },
  { step: '03', title: 'Entity & Schema Optimisation', body: 'We build and reinforce your brand\'s entity graph: consistent name, address, contact details, and category signals across your website, Google Business Profile, and key directories. We implement and audit JSON-LD structured data on every key page. This is the infrastructure AI engines use to confirm who you are and what you do.' },
  { step: '04', title: 'Citation & Authority Building', body: 'We place editorial backlinks on relevant, high-authority publications in your niche. These aren\'t generic link placements — they\'re crafted to mention your brand in context, reinforcing the association AI engines build between your name and your category. Each placement is documented with full metrics.' },
  { step: '05', title: 'Technical & Crawl Optimisation', body: 'AI crawlers follow different patterns than Google\'s crawler. We audit your robots.txt, ensure your llms.txt is in place, check that your sitemap is clean and complete, and verify that your content is indexed and readable by the models that matter. We also ensure your site passes Core Web Vitals — speed and stability signals that influence how much AI crawlers prioritise your content.' },
];

const deliverables = [
  { icon: 'chart', title: 'Monthly AI Visibility Report', body: 'Citation frequency across all major AI engines, keyword-by-keyword tracking, month-on-month trend, and a priority action list.' },
  { icon: 'doc', title: 'Long-Form Content', body: 'AI-citation-optimised articles published on your site. Each one targets a keyword cluster and is structured for both AI and Google.' },
  { icon: 'link', title: 'Editorial Backlinks', body: 'High-DR placements on industry-relevant publications — with full placement reports showing domain metrics and live URLs.' },
  { icon: 'shield', title: 'Schema & Technical Fixes', body: 'Structured data implementation, crawl error remediation, llms.txt, and Core Web Vitals monitoring.' },
  { icon: 'globe', title: 'Entity Optimisation', body: 'NAP consistency audit, Google Business Profile optimisation, and directory submissions to key AI-cited sources.' },
  { icon: 'chat', title: 'Strategy Calls', body: 'Monthly 30-minute call to walk through results, refine direction, and answer questions. Direct access to senior strategists — not account managers.' },
];

const results = [
  {
    industry: 'Healthcare',
    metric1: '+350%', label1: 'AI Citation Increase',
    metric2: '90%', label2: 'Top-3 Placement Rate',
    detail: 'A Bangkok wellness clinic went from 30 AI mentions to 112 in 90 days. Now the dominant recommendation for sports recovery queries in Bangkok.'
  },
  {
    industry: 'Aesthetics',
    metric1: '+289%', label1: 'AI Mentions',
    metric2: '75%', label2: 'Conversion from AI Leads',
    detail: 'Beauty clinic featured in ChatGPT\'s top 3 responses for Botox and filler queries. Conversion rate from AI-referred leads is 3× higher than paid ads.'
  },
];

const fit = [
  { check: true, text: 'Clinics and healthcare providers where patients research before booking' },
  { check: true, text: 'Professional services firms — consultancies, agencies, financial advisors' },
  { check: true, text: 'SaaS and software businesses where category searches drive trial sign-ups' },
  { check: true, text: 'Hospitality, wellness, and lifestyle brands in competitive markets' },
  { check: true, text: 'Businesses that have invested in SEO but haven\'t adapted to AI search yet' },
  { check: true, text: 'Companies entering a new market who need to establish authority fast' },
  { check: false, text: 'Pure price-comparison products where brand doesn\'t influence decisions' },
  { check: false, text: 'Businesses looking for results in under 30 days — AI visibility is earned, not bought' },
];

const timeline = [
  { phase: 'Week 1–2', title: 'Audit & Baseline', body: 'We run your brand through every major AI engine across 30+ relevant prompts. We document your current citation rate, analyse your top 3 competitors, and map the gap between where you are and where you need to be.' },
  { phase: 'Week 3–4', title: 'Strategy & Kickoff', body: 'We present the audit findings, agree on the 90-day strategy, and begin technical work immediately — schema, llms.txt, crawlability fixes. This is the fastest-moving phase and often shows early results within 30 days.' },
  { phase: 'Month 2–3', title: 'Content & Authority Build', body: 'Articles go live on a rolling schedule. Backlink placements begin. We monitor citation frequency weekly and adjust the content angle if we see early data pointing us in a better direction.' },
  { phase: 'Month 3+', title: 'Compound & Optimise', body: 'AI visibility compounds. Each new citation, each new article, each new backlink increases the likelihood of future mentions. We expand into new query clusters and refine what\'s working. Monthly reporting keeps you informed throughout.' },
];

const openCalendly = () => { window.open('https://calendly.com/locully/30min', '_blank'); };

const BookCall = () => <Button variant="outline" onClick={openCalendly}>Book a Call</Button>;

export default function SeoAioPage() {
  return (
    <>
      <Helmet>
        <title>Rank #1 in AI Search: ChatGPT, Perplexity & Google | Locully</title>
        <meta name="description" content="Get named when ChatGPT, Perplexity, and Google AI recommend a business like yours. Locully builds your AI search visibility from the ground up." />
        <link rel="canonical" href="https://www.locully.org/ai-search-visibility" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.locully.org/ai-search-visibility" />
        <meta property="og:title" content="Rank #1 in AI Search: ChatGPT, Perplexity & Google | Locully" />
        <meta property="og:description" content="Get recommended by ChatGPT, Google AI, and Perplexity. Locully builds your AI search presence from the ground up." />
        <script type="application/ld+json">{JSON.stringify(schemaService)}</script>
        <script type="application/ld+json">{JSON.stringify(schemaFaq)}</script>
      </Helmet>

      <Page className="lb-seoaio">
        <Breadcrumb items={[{ label: 'Home', to: '/' }, { label: 'AI Search Visibility' }]} />

        {/* Hero */}
        <PageHero
          as="section"
          eyebrow="AI Search Optimisation"
          visual={<AskAi />}
          title={<>The Agency That Gets You<br />Recommended by AI</>}
          lede="Search has changed. Millions of people now ask ChatGPT, Google AI, and Perplexity for recommendations instead of scrolling a results page."
        >
          <p className="lb-body-lg" style={{ margin: '16px 0 0', maxWidth: 640 }}>
            We build your brand's presence across every AI engine — so when your ideal customer asks, you're the answer.
          </p>
          <div className="lb-hero-cta lb-btn-row">
            <Button cta />
            <BookCall />
          </div>
        </PageHero>

        {/* The New Reality */}
        <Section alt>
          <SectionHeader eyebrow="The Shift" title="Search Has Changed. Permanently." />
          <div className="lb-narrow-copy">
            <p className="lb-body-lg">
              In 2023, Google processed roughly 8.5 billion searches per day. ChatGPT now handles over 100 million queries daily — and growing. Perplexity crossed 100 million monthly users in early 2025. Google's own AI Overviews appear in over 47% of search results.
            </p>
            <p className="lb-body-lg">
              People aren't clicking ten blue links and deciding. They're asking a question and reading one answer. The brand inside that answer wins the lead. The brands not mentioned don't exist.
            </p>
            <p className="lb-body-lg lb-em">
              This isn't a trend to watch. It's the new operating reality. And the window to establish AI search authority before your competitors do is closing.
            </p>
          </div>
          <div className="lb-g3" style={{ marginTop: 44 }}>
            {shiftStats.map(({ stat, label }) => (
              <div key={stat} className="lb-card sm lb-statcard">
                <span className="lb-stat-n">{stat}</span>
                <span className="lb-stat-l">{label}</span>
              </div>
            ))}
          </div>
        </Section>

        {/* How AI Engines Decide */}
        <Section>
          <SectionHeader eyebrow="The Mechanics" title="How AI Engines Choose Who to Recommend" />
          <div className="lb-narrow-copy">
            <p className="lb-body-lg">
              AI language models don't rank pages. They build a model of who the authoritative entities are in a given domain — and when asked a question, they reference those entities.
            </p>
            <p className="lb-body-lg">
              That model is built from everything the AI has read: articles, reviews, forum discussions, news mentions, structured data, and citations across the web.
            </p>
            <p className="lb-body-lg">
              The brands that appear most consistently, in the most credible contexts, with the clearest signals about what they do and who they serve — those are the brands AI models recommend. The good news: these signals can be built. That's what we do.
            </p>
          </div>
          <div className="lb-g2" style={{ marginTop: 44 }}>
            {signals.map(({ icon, title, body }) => (
              <div key={title} className="lb-card">
                <Icon name={icon} />
                <div className="lb-h3-card">{title}</div>
                <p>{body}</p>
              </div>
            ))}
          </div>

          {/* CTA strip 1 */}
          <div className="lb-ctarow lb-ctastrip">
            <p className="lb-body-lg lb-em" style={{ margin: '0 0 22px' }}>
              Want to see where your brand stands in AI search right now?
            </p>
            <div className="lb-btn-row" style={{ justifyContent: 'center' }}>
              <Button cta />
              <BookCall />
            </div>
          </div>
        </Section>

        {/* Our Methodology */}
        <Section alt>
          <SectionHeader eyebrow="Our Approach" title="The Locully Methodology" />
          <div className="lb-narrow-copy" style={{ marginBottom: 24 }}>
            <p className="lb-body-lg">
              We don't have a template. Every client starts with an audit — we measure exactly where you stand in AI search today, identify the gaps, and build a strategy around closing them.
            </p>
            <p className="lb-body-lg">
              The work runs across five interconnected areas. You won't see results from any single one in isolation. AI visibility is built by stacking signals — and we manage all five simultaneously.
            </p>
          </div>
          <div className="lb-stages">
            {methodology.map(({ step, title, body }) => (
              <div key={step} className="lb-stage text-only">
                <div><div className="lb-num">{step}</div></div>
                <div>
                  <div className="lb-h3-stage">{title}</div>
                  <p>{body}</p>
                </div>
              </div>
            ))}
          </div>
        </Section>

        {/* What's Included */}
        <Section>
          <SectionHeader
            eyebrow="Deliverables"
            title="What You Actually Receive"
            lede={'We work on a monthly retainer. Every engagement includes a defined scope — no vague promises, no "strategy only" work without execution.'}
          />
          <div className="lb-g3">
            {deliverables.map(({ icon, title, body }) => (
              <div key={title} className="lb-card">
                <Icon name={icon} />
                <div className="lb-h3">{title}</div>
                <p>{body}</p>
              </div>
            ))}
          </div>
        </Section>

        {/* Results */}
        <Section alt>
          <SectionHeader
            eyebrow="Results"
            title="What Our Clients Have Achieved"
            lede="Numbers from real engagements. Clients are anonymised at their request, but the data is auditable."
          />
          <ProofPanel>
            <div className="lb-proof-cases">
              {results.map(({ industry, metric1, label1, metric2, label2, detail }) => (
                <div key={industry} className="lb-proof-case">
                  <div className="lb-proof-lab">Result · {industry}</div>
                  <div className="lb-proof-pair">
                    <div>
                      <div className="lb-proof-n lb-proof-n-xl">{metric1}</div>
                      <div className="lb-proof-l">{label1}</div>
                    </div>
                    <div>
                      <div className="lb-proof-n lb-proof-n-xl lb-proof-white">{metric2}</div>
                      <div className="lb-proof-l">{label2}</div>
                    </div>
                  </div>
                  <p className="lb-proof-sub">{detail}</p>
                </div>
              ))}
            </div>
          </ProofPanel>

          <div style={{ textAlign: 'center', marginTop: 30 }}>
            <Button variant="text" href="https://locully-client-success-m8a58k2.gamma.site/" target="_blank" rel="noopener noreferrer">
              View full case studies
            </Button>
          </div>

          {/* CTA strip 2 */}
          <div className="lb-ctarow lb-ctastrip">
            <p className="lb-body-lg" style={{ margin: '0 0 22px' }}>
              <span className="lb-em">Ready to build your AI search presence?</span>{' '}
              <span>Free audit, no commitment.</span>
            </p>
            <div className="lb-btn-row" style={{ justifyContent: 'center' }}>
              <Button cta />
              <BookCall />
            </div>
          </div>
        </Section>

        {/* Who It's For */}
        <Section>
          <SectionHeader
            eyebrow="Fit"
            title="Who This Is Right For"
            lede="We work best with businesses where trust plays a central role in the buying decision — and where an AI recommendation carries real weight."
          />
          <div className="lb-g2" style={{ alignItems: 'start' }}>
            <div className="lb-fit yes">
              <ul className="lb-list lg">
                {fit.filter((f) => f.check).map((f) => <li key={f.text}>{f.text}</li>)}
              </ul>
            </div>
            <div className="lb-fit no">
              <ul className="lb-list dash lg">
                {fit.filter((f) => !f.check).map((f) => <li key={f.text}>{f.text}</li>)}
              </ul>
            </div>
          </div>
          <p className="lb-body-lg" style={{ textAlign: 'center', maxWidth: 680, margin: '36px auto 0' }}>
            If you're not sure whether this fits, book a 30-minute call. We'll tell you honestly — and if it's not the right move for your business right now, we'll say so.
          </p>
        </Section>

        {/* Process Timeline */}
        <Section alt>
          <SectionHeader eyebrow="Process" title="How We Get Started" />
          <div className="lb-timeline">
            {timeline.map(({ phase, title, body }) => (
              <div key={phase} className="lb-tl-row">
                <div className="lb-tl-phase"><span className="lb-tag">{phase}</span></div>
                <div>
                  <div className="lb-h3">{title}</div>
                  <p className="lb-body-lg" style={{ margin: 0 }}>{body}</p>
                </div>
              </div>
            ))}
          </div>
        </Section>

        {/* FAQ */}
        <Section>
          <SectionHeader eyebrow="FAQ" title="Common Questions" style={{ marginBottom: 40 }} />
          <FAQ items={faqs} />
        </Section>

        {/* CTA + lead form */}
        <LeadForm
          eyebrow="Free AI visibility check"
          title="Start With a Free Audit"
          lede="We'll show you exactly where your brand stands in AI search today — ChatGPT, Perplexity, Google AI, and Gemini — and what it would take to rank #1."
          footer={(
            <div className="lb-ctarow" style={{ marginTop: 28 }}>
              <BookCall />
            </div>
          )}
        />

        <Footer />
      </Page>
    </>
  );
}
